name: 'LensDX Docs Action'
description: 'Publish docs and standards to LensDX'
branding:
  icon: 'bar-chart-2'
  color: 'black'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/catalog.sh
      shell: bash
    - run: ${{ github.action_path }}/standards.sh
      shell: bash